### ISSUE TITLE
Correctly constructed JSON objects unable to be read by binanceAPI. Error code 3 returned

### ISSUE THREAD

**Issue by JacksonHR2000** [binance-us/binance-official-api-docs#34]
This JSON object
```
var paramJSON = {
	"method": "SUBSCRIBE",
	"params": [
		"btcusd@kline_1m",
		"ethusd@kline_1m",
		"solusd@kline_1m",
		"dogeusd@kline_1m",
		"adausd@kline_1m",
		"vetusd@kline_1m",
		"bnbusd@kline_1m"
	],
	"id": "10"
}
```

is unable to be read by the Binance parser, despite being a valid JSON object. I have also tried sending the same message with the parenthesis removed from the ID, but that does not work either.

I am using the inbuilt javascript WebSocket class to handle my class, and I am sending this message to a connected stream using this code:
`stream.send(paramJSON)`

Furthermore, I have also tried sending the example message from this project's documentation, but that is also returned with error code 3.
```
var paramJSON = {
  "method": "SUBSCRIBE",
  "params": [
    "btcusdt@aggTrade",
    "btcusdt@depth"
  ],
  "id": 1
}
```

I am certain that I am sending these JSON files over a valid connection. What could be going on here?

**Comment by JacksonHR2000** [comment]
Issue fixed. I was not sending my JSON as a string.

**Comment by rorysan333** [comment]
Thank you very much


Sent from the all new AOL app for iOS


On Friday, June 25, 2021, 1:50 PM, JacksonHR2000 ***@***.***> wrote:




Issue fixed. I was not sending my JSON as a string.
